services:
  traefik:
    image:            traefik
    container_name:   traefik
    restart:          unless-stopped
    command:    
      - --api 
      - --logLevel=error    
      - --defaultEntryPoints=https
      - --docker
      - --web
      - --docker.watch
      - --docker.exposedByDefault=${TRAEFIK_EXPOSED_DEFAULT}
      - --docker.domain=${TRAEFIK_DOMAIN}
      - --entryPoints=Name:https Address::${TRAEFIK_PORT_443} Compress:true TLS
      - --acme.entrypoint=https
      - --acme.caServer=https://acme-staging.api.letsencrypt.org/directory
      - --acme.storage=acme.json
      - --acme.domains=${TRAEFIK_DOMAIN}
      - --acme.onHostRule=true
      - --acme=${TRAEFIK_ACME_ENABLE}
      - --acme.email=${TRAEFIK_ACME_EMAIL}
      - --acme.${TRAEFIK_ACME_CHALLENGE}
      - --acme.${TRAEFIK_ACME_CHALLENGE}.provider=${TRAEFIK_ACME_CHALLENGE_PROVIDER}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERSHAREDDIR}:/shared
    cap_add:
      - NET_ADMIN